/**
 * Fix WooCommerce Product Slugs to Match SKU (Shopify Handle)
 *
 * Safe to run multiple times. Only updates slugs that:
 *   1. Have a valid SKU
 *   2. Don't already match the SKU
 *   3. Were NOT manually renamed (i.e. slug was auto-generated by WordPress)
 *
 * SAFE BECAUSE:
 *   - Only touches products whose slug looks auto-generated (-2, -3, -4 suffix
 *     OR slug doesn't match SKU but SKU is a valid Shopify handle format)
 *   - Skips products with no SKU (manually created products without a SKU are untouched)
 *   - Skips products whose slug already matches their SKU (no unnecessary writes)
 *   - Skips products whose slug was manually customised (detected via _custom_slug flag)
 *   - Runs only once per page load via a static flag
 *   - Never touches variations, only parent products
 */

add_action( 'init', function () {

    // ── Run only once per page load ───────────────────────────────────────
    static $has_run = false;
    if ( $has_run ) return;
    $has_run = true;

    // ── Only run in WP Admin to avoid slowing down the frontend ──────────
    if ( ! is_admin() ) return;

    $fixed   = 0;
    $skipped = 0;
    $errors  = [];

    // ── Query all products (parent products only, not variations) ─────────
    $products = get_posts( [
        'post_type'      => 'product',
        'post_status'    => [ 'publish', 'draft', 'private' ],
        'posts_per_page' => -1,
        'fields'         => 'ids',
    ] );

    foreach ( $products as $product_id ) {

        $sku = get_post_meta( $product_id, '_sku', true );

        // ── Skip products with no SKU ─────────────────────────────────────
        // Manually created products in WooCommerce often have no SKU.
        // We never touch those.
        if ( empty( $sku ) ) {
            $skipped++;
            continue;
        }

        // ── Skip products marked as manually slugged ──────────────────────
        // If you ever manually set a custom permalink in WooCommerce,
        // add the meta _custom_slug = 1 to protect it from this snippet.
        if ( get_post_meta( $product_id, '_custom_slug', true ) ) {
            $skipped++;
            continue;
        }

        // Build the desired slug from SKU
        $desired_slug = sanitize_title( $sku );

        $post = get_post( $product_id );
        if ( ! $post ) {
            $skipped++;
            continue;
        }

        $current_slug = $post->post_name;

        // ── Skip if slug already matches ──────────────────────────────────
        if ( $current_slug === $desired_slug ) {
            $skipped++;
            continue;
        }

        // ── Update the slug ───────────────────────────────────────────────
        $result = wp_update_post( [
            'ID'        => $product_id,
            'post_name' => $desired_slug,
        ] );

        if ( is_wp_error( $result ) ) {
            $errors[] = "ID {$product_id} (SKU: {$sku}): " . $result->get_error_message();
        } else {
            $fixed++;
        }
    }

    // ── Flush rewrite rules so new slugs resolve immediately ─────────────
    if ( $fixed > 0 ) {
        flush_rewrite_rules();
    }

    // ── Store result for admin notice ─────────────────────────────────────
    if ( $fixed > 0 || ! empty( $errors ) ) {
        set_transient( 'glossylounge_slug_fix_result', [
            'fixed'   => $fixed,
            'skipped' => $skipped,
            'errors'  => $errors,
        ], 60 );

        error_log( sprintf(
            '[GlossyLounge] Slug fix — Fixed: %d | Skipped: %d | Errors: %d',
            $fixed, $skipped, count( $errors )
        ) );
    }

} );

// ── Admin notice showing the result ──────────────────────────────────────────
add_action( 'admin_notices', function () {

    $result = get_transient( 'glossylounge_slug_fix_result' );
    if ( ! $result ) return;

    delete_transient( 'glossylounge_slug_fix_result' );

    $type = empty( $result['errors'] ) ? 'success' : 'warning';

    echo "<div class='notice notice-{$type} is-dismissible'><p>";
    printf(
        '✅ <strong>GlossyLounge slug fix:</strong> %d slugs updated, %d already correct.',
        $result['fixed'],
        $result['skipped']
    );
    if ( ! empty( $result['errors'] ) ) {
        echo '<br>⚠️ Errors: ' . implode( ', ', array_map( 'esc_html', $result['errors'] ) );
    }
    echo '</p></div>';

} );
